
name: OIDC Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  oidc-test:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show GitHub branch
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::287870619366:role/oidc-role-murthy
          aws-region: ${{ env.AWS_REGION }}

      - name: Test AWS credentials
        run: aws sts get-caller-identity  
